### ISSUE TITLE
add pre-OOP task

### ISSUE THREAD

**Issue by AMashoshyna** [kottans/frontend#106]
This issue is an off-spring from #92 

As discussed, we are looking for a task which would be relatively easy but still would prepare students for more complex topics. Please find below the list of existing proposals for tasks:
1. Football ([description](https://github.com/kottans/frontend/issues/92#issuecomment-429604432))
2. Interactive menu ([description](https://github.com/kottans/frontend/issues/92#issuecomment-429604432))
3. User cards ([description](https://github.com/kottans/frontend/issues/92#issuecomment-429604432))
4. mini-spreadsheet ([description](https://github.com/kottans/frontend/issues/92#issuecomment-429609553))

**Comment by OleksiyRudenko** [comment]
Please, add
5. A dog, a cat, a woman, a man, and an optional cat-woman ([description](https://github.com/kottans/frontend/issues/92#issuecomment-429547230))

Basically, I have already a [template repo](https://github.com/OleksiyRudenko/a-tiny-JS-world/blob/master/README.md) for this. And ready to create a task within the course based on that.

Yet another idea: pre-OOP may offer a choice of tasks, so students could choose whatever they feel comfortable with in terms of background and own time-to-complete estimation.

P.S. Thank you for making off-springs #92. Gonna somehow wind it up.

**Comment by OleksiyRudenko** [comment]
@IgorKurkov One of the methods is to do a PR with a task. The point is just not adding it to syllabus (i.e. any `/contents.md` or `/syllabus.md`). Look at this [PR](https://github.com/kottans/frontend/pull/109) as a reference case.
