### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/frontend#108]

**Comment by OleksiyRudenko** [comment]
I shall suggest the content and let's then decide on the appropriate place for it.

**Comment by OleksiyRudenko** [comment]
Next steps (when github is back to us again :) ):
- Add https://github.com/leonardomso/33-js-concepts "pr's welcome" label as per [suggestion](https://github.com/kottans/frontend/pull/126#issuecomment-431747264)
- Add link to http://makeapullrequest.com/
- Add link to subset of https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github

**Comment by cidre** [comment]
Good work! :+1: 
Sorry, may I point out some suggestions without PR? :)
1) Please, feel free adding any comments. -> Please, feel free **to add** any comments.
2) It's important that commits be atomic to keep the history clean. ->  It's important that commits **are** atomic to keep the history clean.
3) Below is a short guide on squashing commits into a clean history. -> **Listed** below is a short guide on squashing commits into a clean history.

**Comment by OleksiyRudenko** [comment]
Thank you!

And thank you for your suggestions. Well taken into consideration. However, I would say the squashing guide here lists some steps rather than gets listed [among others]. _-ing_ is pretty OK here. Like _feel free inquiring me_.
