### ISSUE TITLE
Move course to gitbook

### ISSUE THREAD

**Issue by viktor-yakubiv** [kottans/frontend#114]
Somewhere it was suggested. As far as I remember, by @sudodoki.

The idea is to add meaningful names to tasks, what we already did, and generate contents with normal numbering by [GitBook](https://www.gitbook.com). After that we can host course on web.

**Comment by yevhenorlov** [comment]
Related to #90
I'd be happy to do this task if that's okay. Should we postpone this till after Sunday meeting? We probably need to decide on the final structure first.
