### ISSUE TITLE
Review online phase tasks completion evidence requirements

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/frontend#142]
A remote (online) phase task requires evidence(s). Each task must specify evidences to add to student's course repo that are (a) screenshot of video course (e.g. Udacity) completion, and/or (b) screenshot of online tasks (e.g. codewars) completion, and/or (c) link to a task code base repo (e.g. Memory Pair game, OOP exercise, Friends app).

Instruction also should say what student has to report to students chat.

Tasks descriptions need to be revised and conform to the above.

**Comment by suchov** [comment]
maybe codewars can be provided just with the nickname and be in a Kottans clan?

**Comment by zonzujiro** [comment]
Also, tasks with code must have approve from one of the mentors
