### ISSUE TITLE
Add basic IDE setup guide

### ISSUE THREAD

**Issue by AMashoshyna** [kottans/frontend#169]
Add instructions on how to setup IDE:
- package.json
- eslint
- prettier
- ...

**Comment by AMashoshyna** [comment]
I will be available to fix this issue on Monday 12/11 earliest. If anyone has time to do it earlier, please reassign the issue.

**Comment by zonzujiro** [comment]
IMO, such staff is not mandatory for students right now - `package.json`, `,eslintrc`, etc. 

Maybe `prettier`, but... nah.

I know that I was a person who proposed this. I am sorry 👼
