### ISSUE TITLE
JS basics - Algo Pig Latin: add a note on Y letter

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/frontend#175]
In English letter Y may represent both vowel and consonant. Many non-native speakers stick to considering it a vowel and therefore get stuck at *Intermediate Algorithms Scripting: Pig Latin* exercise where Y is treated as a consonant.

Students' efforts in figuring this issue out seem to be not paying so the proposal is to add a relevant NB to the JS Basics task description to remove the unnecessarry hassle.

**Comment by zonzujiro** [comment]
I am sorry, but wat is `NB`? :)

**Comment by OleksiyRudenko** [comment]
[Nota Bene](https://en.wikipedia.org/wiki/Nota_bene), a shorter form of **Please, pay special attention and take well into consideration** )

**Comment by OleksiyRudenko** [comment]
Resolved by #177
