### ISSUE TITLE
Additional P2P learning group for FE course 2019

### ISSUE THREAD

**Issue by zonzujiro** [Kottans/frontend#227]
⚠️ Read this issue first - https://github.com/kottans/frontend/issues/240 ⚠️ 

We all have a different amount of free time, different level of knowledge. It is normal. So not all who wanted to be a part of FE course finished necessary tasks.

We have decided, that we can't abandon all who wants studying with us. Right now we are working on idea how to help this group of people. 

You can be on the first task or on the last. Don't matter. If you want to study in this additional group - proceed to https://github.com/kottans/frontend/issues/240.

Share the knowledge.

**Comment by jsmuse** [comment]
😼

**Comment by DJStar77** [comment]
May the force be with us!

**Comment by mazvira** [comment]
Cool!!))
Thank you!)
Of, course, yes))

**Comment by olencha** [comment]
I'm in🌟
You're the best ❤️
Thank for this opportunity!

**Comment by frostwolm** [comment]
+

**Comment by dartist21** [comment]
🐢

**Comment by daria-strikun** [comment]
You are super cool! :heart_eyes:
Thank you for this oppotrunity!
Count me in :smiley_cat:

**Comment by Orlandis** [comment]
Hi
I want to continue my studies

**Comment by feroxes** [comment]
Hi!
Me too!

**Comment by dizerfree** [comment]
Hello! I also did not have time and I will continue to study, I'd like to do it with you.
You set a good pace and the right motivation. Thank you for it

**Comment by AnnaGrynchuk** [comment]
I want study with you too)

**Comment by Anto0n** [comment]
I want to carry on!

**Comment by PAtrofimov** [comment]
Hi, I am ready to continue with pleasure!

**Comment by Roman-Halenko** [comment]
+1

**Comment by DmitryLevercode** [comment]
+

**Comment by alexdefender** [comment]
I'll be with you everywhere!

**Comment by Olga-Garanko** [comment]
+1

**Comment by sayckl** [comment]
🦄

**Comment by SvitlaM** [comment]
Great idea!Im in!Thank you

**Comment by borelord** [comment]
I would greatly appreciate a chance to continue :3
So yeah, I am definitely in!

**Comment by kris-almort** [comment]
I'm in! :З

**Comment by trnvld** [comment]
+1

**Comment by Temu4** [comment]
+1 =О.О=

**Comment by AndewTu** [comment]
Great! +1
Thank you!

**Comment by Murenka** [comment]
+1)

**Comment by LiliiaKondurova** [comment]
+1! Thank you!

**Comment by JulsT** [comment]
+1 🐱

**Comment by earthaddicted** [comment]
+1  Thank you very much for such opportunity!

**Comment by Goralive** [comment]
I'm in. Whant to finish when will be more time

**Comment by IraKovalenko** [comment]
+1!

**Comment by Eugene50** [comment]
I wish to!)))

**Comment by AlexNugda** [comment]
+1
Thank you very much!

**Comment by zophrox** [comment]
+1

**Comment by quentinksi** [comment]
Hello
I want to study
Thank you!

**Comment by mfialko** [comment]
+

**Comment by Jyuart** [comment]
I'm in!
Great opportunity, thank you!

**Comment by kotyk** [comment]
+ 😻

**Comment by babayK0** [comment]
I do not know if I did enough, that's why i am with you ! :smile_cat:

**Comment by BachiOlga** [comment]
I want to be on your team. Thanks for this opportunity 😸

**Comment by Zakkarat** [comment]
Wow, that's cool! 
Just on the start of tasks here, but I look forward for new challenges. 
I'm in!

**Comment by ipgpt** [comment]
+1

**Comment by m4dmeds** [comment]
Hello! Thank you very much. I want to study.

**Comment by thinker-tinker4** [comment]
Hi there.

Count on me!

**Comment by mxmgny** [comment]
+1 =)

**Comment by V1taliy** [comment]
Hi, I want to finish this offline course if its possible. Add me please =)

**Comment by Roka20012** [comment]
Hello)+1)

**Comment by allamarana** [comment]
+1!

**Comment by AwesomeCrystalCat** [comment]
Hey, kottans!
Would like to join you.
Thanks!

**Comment by SadovnichiyDmitry** [comment]
++

**Comment by maryna-dumenko** [comment]
I'm in!  Thank you for this opportunity!

**Comment by olya-sonrie** [comment]
+1 😺
Thanks!

**Comment by zonzujiro** [comment]
It is not a complete idea, just telling you that we are working on a problem and updating current status.

We have discussed possible options on how we can help all people. 😄  Taking into action, that we already have one full course and we don't have endless time opportunities, we have decided, that we can stick to an idea of peer-to-peer education. 

This means that the main work with code reviews will be done by students of p2p and main courses. 
We can teach you how to do code-reviews, what to look for, etc. If some lectures are needed - we can help to arrange them, which means that we can find somebody who's going to read it. If you need someplace to meet offline - we can help find such a place.

For now, it is just general vision with two ideas behind:

1. Provide possible help to students who want to learn but didn't have possibility to finish online course in time. Long story short - we just want you to keep learning and do what you like.
2. Create a place, where anybody can come in any time and learn programming, where you can call friends and be sure that everything will be ok.

Last, but not least, Kottans are known as a knowledge-sharing community, not a usual IT course. So we will be glad if someone is ready to put in the work and help us. 😉

So, we are looking for your opinion.

We will provide more details later on this or next week. Meanwhile, you can continue with tasks.

Have a good day.

**Comment by makolvik** [comment]
+1 Good idea!

**Comment by Kanaraa** [comment]
I'm in ^_^

**Comment by wely88** [comment]
Will be happy to have a chance to study!

**Comment by Lerka-B** [comment]
+1

**Comment by Drynka** [comment]
Hi! 
I'm in!

**Comment by sortedlist** [comment]
+1

**Comment by BachiOlga** [comment]
^ _ ^

**Comment by RINAMEGA** [comment]
Было много работы, курс пройти не получилось,  сейчас готова

**Comment by Evgeniy241984** [comment]
+1

**Comment by Evgeniy241984** [comment]
+1

**Comment by Evgeniy241984** [comment]
It will be pleasure 
+1

**Comment by Marinichenko** [comment]
+1

**Comment by MalyshkoPavel** [comment]
Thank you for this great opportunity.
I'm in ;)

**Comment by Borabola** [comment]
+1

**Comment by JuliaVorotchenko** [comment]
+1 
Thanks)

**Comment by Yojj** [comment]
I wish to!)

**Comment by Somoth** [comment]
I'm in :)

**Comment by AcidOctane** [comment]
+

**Comment by BeMoreHuman** [comment]
+1

**Comment by Yojj** [comment]
привет! как бы собраться и roadmap обсудить?  :)

**Comment by mysterious25** [comment]
Hello!
I'm in!

**Comment by korotushak96** [comment]
I'm with you =)

**Comment by Misperia** [comment]
I'm in :)

**Comment by maab2198** [comment]
+1😊

**Comment by filianna** [comment]
I'm with you

**Comment by filianna** [comment]
Thank you!

**Comment by AndyFerenchuk** [comment]
+

**Comment by AndyFerenchuk** [comment]
I would like to participate, if it is possible

**Comment by Vitieka** [comment]
I'm with you

**Comment by AQuaZar** [comment]
I would like to take part 🙂

**Comment by alizzle** [comment]
I'm in! c:
