### ISSUE TITLE
Add links to p2p homeworks repo

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/frontend#234]
Practical tasks instructions should contain links to both frontend-2019-homeworks and frontend-2019-p2p repos.

**Comment by zonzujiro** [comment]
Right now we have the same text in every task. I believe we should use DRY and make two separate files with instructions - one for p2p and one for the main course. And then just put links inside every task.

**Comment by OleksiyRudenko** [comment]
@zonzujiro 
Initialized [kottans/frontend-2019-p2p](https://github.com/kottans/frontend-2019-p2p) repo
