### ISSUE TITLE
Meeting of p2p students

### ISSUE THREAD

**Issue by zonzujiro** [kottans/frontend#258]
**What:** Meeting of P2P course participants. Let's discuss tasks, ask questions about the course, etc.

**Where** [Chasopys](http://www.chasopys.ua/)

![image](https://user-images.githubusercontent.com/2997359/52476648-eef3d200-2ba7-11e9-9757-ef7db54bf3c0.png)

[Map](https://2gis.ua/kiev/geo/15059546909180501%2C30.514972%2C50.439523?queryState=center%2F30.514054%2C50.43955%2Fzoom%2F18)

**When:** February 15. Start at 19:00-19:30

***Do I need a laptop:*** As you wish

**Who invited:** everyone who left comments here. Newcomers are welcome too :smiley_cat: 

_If you have any question - fill free to ask in this issue._

**Comment by Shramkoweb** [comment]
Iam in!

**Comment by olencha** [comment]
😺

**Comment by kris-almort** [comment]
+

**Comment by Oodmincheg** [comment]
+

**Comment by Temu4** [comment]
+

**Comment by Temu4** [comment]
I'm with you!

**Comment by babayK0** [comment]
+1

**Comment by nazmariam** [comment]
+

**Comment by prhokay** [comment]
+

**Comment by Zakkarat** [comment]
I'm in!

**Comment by Roka20012** [comment]
Hello :) +1

**Comment by StebeLski** [comment]
+

**Comment by Feliciter** [comment]
Hello :) +1

**Comment by daria-strikun** [comment]
Hi! +1
