### ISSUE TITLE
Broken link to material "Как учиться и справляться с негативными мыслями"

### ISSUE THREAD

**Issue by ChukkyKatz** [kottans/frontend#269]
As student I try to go by link [Как учиться и справляться с негативными мыслями](https://hexletguides.github.io/learning/) in "Git and GitHub Intro" section but received error 404

**Comment by ChukkyKatz** [comment]
![screnshot1](https://user-images.githubusercontent.com/27965478/57013222-302dd800-6c13-11e9-9acc-a46b2d39991d.jpg)
![screenshot2](https://user-images.githubusercontent.com/27965478/57013300-90bd1500-6c13-11e9-8564-5de0d2a2988e.JPG)

**Comment by AMashoshyna** [comment]
Fixed, thanks!
