### ISSUE TITLE
Git and Github tasks: wrong legacy name and link for Udacity Git course

### ISSUE THREAD

**Issue by coroboX** [kottans/frontend#273]
When I clicked to 

> 1. Finish the course [How to use Git and GitHub](https://www.udacity.com/course/how-to-use-git-and-github--ud775)

in the [Git and GitHub](https://github.com/kottans/frontend/blob/master/tasks/git-intro.md) task list, 
it's redirecting to the [Version Control with Git](https://www.udacity.com/course/version-control-with-git--ud123) course

**Comment by suchov** [comment]
https://github.com/kottans/frontend/pull/274
