### ISSUE TITLE
Add links to related youtube casting

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/frontend#276]
Some tasks were highlighted during the offline part of the course in 2019.
It might be of great help for the self-learners if these tasks/modules contained direct links to relevant clips from [Frontend 2019 playlist](https://www.youtube.com/playlist?list=PLS8sEUxbfFY-Xjv3JPLUAgMqGgF8CbcjZ)

Other playlist to consider as a source:
- [p2p](https://www.youtube.com/playlist?list=PLS8sEUxbfFY8--EfP3JfjgL0vbGPsfnrs)
- [Frontend 2018](https://www.youtube.com/playlist?list=PLS8sEUxbfFY8sOR7is8RGl1neydJRtQWV)

Each fragment might be a screenshot (frame) from the video linked to a video per se.

Skills to have to accomplish:
- MarkDown
- git/GitHub: forking, contributing via a pull request

**Comment by OleksiyRudenko** [comment]
Perhaps we need a set of covers published somewhere along for easier access.
[kottans/artifacts](https://github.com/kottans/artifacts) seems to be an appropriate place to store cover images.

**Comment by nazmariam** [comment]
Hi! Could I add links to related YouTube casting?

**Comment by OleksiyRudenko** [comment]
@nazmariam sure. All yours!

**Comment by OleksiyRudenko** [comment]
@nazmariam I'd suggest that we first have any one module with a video preview and link in PR.
 This would allow us to align the overall view, location within the file etc. and save your efforts.
Once aligned you will complete other modules + videos having better and aligned guidelines.

**Comment by nazmariam** [comment]
Ok! Got it.
