### ISSUE TITLE
Change assignment in tasks/html-css-popup.md

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/frontend#278]
The problem:
Some users have their sub-domain under github pages (github.io) banned for the task being accomplished and code published resembled phishing attempt.
[proof](http://feroxes.github.io/)

Action points:
1. change the [assignment](https://github.com/kottans/frontend/blob/master/tasks/html-css-popup.md) so that the result wouldn't resemble anything from google or other big bro
1. identify all users that suffered and suggest support (discard the source code and re-publish gh-pages; address google support for un-ban)

An appropriate student's work from the past course might be a good source of illustrations.

Alternative is just to draw mockups using icons from e.g. https://fontawesome.com/ or similar resource (colored icons are better).

**Comment by OleksiyRudenko** [comment]
Preparing [a model app](https://github.com/OleksiyRudenko/hooli-style-popup) based on [task implementation](https://github.com/kaizengami/Google-style-Popup) by [kaizengami](https://github.com/kaizengami).

[Issues to complete](https://github.com/OleksiyRudenko/hooli-style-popup/issues).

**Comment by ultrinnan** [comment]
Can I take this please?)
