### ISSUE TITLE
Kotanu

### ISSUE THREAD

**Issue by NazarProg** [kottans/frontend#296]

**Comment by OleksiyRudenko** [comment]
@NazarProg will you expand on the issue?

**Comment by NazarProg** [comment]
> @NazarProg will you expand on the issue?


What exactly the issue?

**Comment by zonzujiro** [comment]
Will close this one :)

**Comment by OleksiyRudenko** [comment]
@NazarProg issue is a bug report or an enhancement proposal. The issue you have opened doesn't contain any details on any bug or on any enhancement, so the purpose wasn't clear. That's why I suggested to expand on it to have more clarity on what you might have had on your mind.
