### ISSUE TITLE
Add frontend definitions dictionary to the README file

### ISSUE THREAD

**Issue by yevhenorlov** [kottans/frontend#33]
Someone mentioned the issue of unfamiliar frontend terminology at today's meeting, perhaps it would be a good idea to add a link to some sort of a dictionary. 
There's [a good example of such dictionary](https://github.com/web-standards-ru/dictionary) maintained by web-standards.ru community. It provides not only definitions of frontend terminology, but also pretty sensible translations of those terms.
I suggest that we add a link to it in README header (alongside gitter button, awesome list button etc.). If that's ok, I'd be happy to make a PR.

**Comment by cidre** [comment]
+1

**Comment by suchov** [comment]
yeh, @yevhenorlov go ahead and create a PR
