### ISSUE TITLE
General inquiry: remote vs local presence

### ISSUE THREAD

**Issue by zerkms** [Kottans/frontend#4]
(Asking for a friend)

I cannot find a confirmation myself, could you please clarify whether it's possible to attend for somebody that's not in Kyiv?

Thanks.

**Comment by suchov** [comment]
Hi, @zerkms your friend can participate online but he/she will miss the part that will be discussed in group + some of the workshops.

**Comment by Kosstiantyn** [comment]
Sorry for the long answer.
I don't know. I think this is impossible because it's offline course. But
everything is possible.)))
