### ISSUE TITLE
Завдання "Адаптивний Web Design": не працює посилання на додатковий матеріал

### ISSUE THREAD

**Issue by dmytro-botnarenko** [kottans/frontend#417]
У розділі 4. [Responsive Web Design](https://github.com/kottans/frontend/blob/2022_UA/tasks/html-css-responsive.md) в додаткових матеріалах:

* не працює посилання [A simple explanation of High DPI screens](https://broken-links.com/2013/10/02/simple-explanation-high-dpi-screens/)
* посилання на [11 things I learned reading the flexbox spec](https://hackernoon.com/11-things-i-learned-reading-the-flexbox-spec-5f0c799c776b) робить редирект на головну сторінку сайту (мабуть стаття змінила адресу або прибрана)

**Comment by suchov** [comment]
@dmytro-botnarenko дякую, якщо ще зашлете PR - буде подвійне ❤️
