### ISSUE TITLE
HTML і CSS практика: Hooli-style Popup - http://www.hooli.xyz/ - ERROR The requested URL could not be retrieved

### ISSUE THREAD

**Issue by rahmanoff** [kottans/frontend#425]
Looks like http://www.hooli.xyz out there...

**Comment by artem-trubin** [comment]
It seems that Hooli's fictional site is now down. Is there any reason we link this task to Hooli anyway, @suchov ? Maybe we can remove the mention of Hooli at all since everything for the tasks, including screenshots is IN the task itself?

**Comment by OleksiyRudenko** [comment]
Thanks for pointing this out. Removed as it is not critical for the task comprehension and completion.
