### ISSUE TITLE
Tag current master with "v.2017-2018" and create a release

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/frontend#88]

**Comment by suchov** [comment]
@OleksiyRudenko tag added, and on github already, but what do you mean by "create a release"?

**Comment by OleksiyRudenko** [comment]
@suchov , seems like github is smart enough to create a release with no additional efforts: https://github.com/kottans/frontend/releases

Issue resolved. Thank you!

**Comment by suchov** [comment]
Great, thanks!
