### ISSUE TITLE
Add git workshop

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/frontend#89]
There is a git course in the program and many students complete createRepo-makePR task (task 0).
However, many do not benefit from git branching, commit squashing, stashing and undoing in git style in their daily work. Single day workshop might help establish good habits.

Possible topics for the workshop:
- using branches for experiments and easy roll-back
- merge vs rebase
- commit frequently and squash
- oh shit, git
- conflict resolution and collaboration basics

**Comment by viktor-yakubiv** [comment]
It's possible on the first lecture but it's not possible on remote mode. Let's postpone it.

According to the idea of 'Stupid Wednesdays' we can give some lectures on a another day. I suggest to dedicate the first this kind of Wednesday to Git practices.

**Comment by IgorKurkov** [comment]
I think its great idea for first offline lessons. We can set it to schedule plan as a suggestion for some first lectures,  - stashing, undoing and branch creating/switching practice. Great idea  :)

**Comment by IgorKurkov** [comment]
so - todo: bootstrap schedule plan for offline lessons - insert this idea as suggested lecture

**Comment by yenobi** [comment]
I do not think it makes sense to create more lectures on this topic after the basic lecture on git, especially after udacity course. Workshops maybe, yes. Someone from the new mentors (hinting at myself) can, after half a week (the time when someone tried and failed in the git, 1-2 days in fact) spend another short workshop to practice show how this works on a “real” or truly real project.

**Comment by IgorKurkov** [comment]
@yenobi  so we need some like thesaurus - lectures = theory, workshop = practice, lessons = the whole instance of teaching time in 2-4 hours which contains workshop/practice/q&a/etc or something like this. 
I mean only to do single workshop+lecture in one place as suggested Oleksiy. Udacity brings only basic knowledge, but not truly practice, so it will be very helpful for students I think. You can discuss this with @OleksiyRudenko and make it both. It will be great I guess:)

**Comment by OleksiyRudenko** [comment]
As per our offline discussion last week it seems good to have this as a workshop during intramural part of the course. During pre-course students will face many situations that this workshop would address.

From the other hand many of the students may know how to resolve conflicts, undo things in git style etc. so it is good idea to run it on Wednesday as per @viktor-yakubiv suggestion above.

I shall add the task to repo via PR. Subject to further discussion and improvement of course.

**Comment by OleksiyRudenko** [comment]
Just cannot invite all discussion participants as reviewers. Please, feel free commenting on PR #102
