### ISSUE TITLE
Bring structure into tasks list to improve manageability

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/frontend#90]
Problems:
1. Adding a task in the middle of the list will require all tasks renumbering
2. No clear boundary between purely remote and meetup supported tasks (e.g. for publishing purposes)
3. No clear boundaries between topics (tasks aren't grouped per topic)
4. All tasks look (currently are) mandatory

Proposal:
1. Introduce task codes instead of task ordinal number in both file names and 
2. Mark task optionality (e.g. Website Performance Optimization may be Optional or Nice-to-Know) in task description

Task code suggestion. 
Task code comprises 4 digits, e.g. `1230` where:
* `1` is course phase (e.g. `0` - remote, `1` - meetup supported)
* `2` is topic ordinal code (e.g. `1` in phase `0` - misc basics (git PR, Linux CLI...), `2` - HTML/CSS,  `3` - OOP)
* `30` task code. Current tasks codes will look like `10`, `20`, `30` etc. When any new task to be added between task `0210` and task `0220` it will be coded `0115`.

Current tasks table of contents may look like following (current task number is in brackets):

# 0000 Remote tasks
## 0100 General Basics
* 0120 Git basics (0)
* 0130 Linux CLI and Networking (01)
* 0140 VCS (hello gitty), GitHub and collaboration (02)
## 0200 Frontend basics
* 0220 Intro to HTML & CSS (03)
* 0220 Responsive Web Design (04)
* 0230 Intro to JS (05)
## 0300 Frontend Advanced
* 0320 Object oriented JS (06)
* 0330 Offline Web Applications (nice-to-know) (07)
* 0340 Real project! Memory pair game (08)
* 0350 Website Performance Optimization (nice-to-know) (09)
* 0360 Real project! Weather app (10)
# 1000 Meetup supported tasks 
## 1100 Basic skills enhancement
* 1120 Mastering HTML 5 forms (11)
* 1130 Responsive Layouts (12)
## 1200 Advanced
* 1220 Pizza App: Login and Registration (13)
* 1230 Pizza App: Pizza Creation (14)
* 1240 ReactJS Weather App (15)
* 1250 React + Redux

Filling a gap between Intro to JS (05) and OOP (06) will then be as easy as adding `0240 Advanced JS` to the table of contents and file `task0240.md`. Or `0310 Advanced JS` - depending on how we qualify the complexity of the task.

**Comment by OleksiyRudenko** [comment]
> _By the way, where have you left 1110?_

@viktor-yakubiv just some more space for possible prepending with topics.

**Comment by viktor-yakubiv** [comment]
Anyway, I think that task structure is good for us but is really hard to understand event with guidelines to regular people who just opened the repository link. Let's leave numbering for regular people, e.g. 1,2,3..., and use this guideline to build clear plan of the course.

**Comment by viktor-yakubiv** [comment]
Opposite suggestion, what I was thinking about, to create _Contents_ file or a section in _README.md_ what people can read and clearly understand what is the course about and what exactly they are going to learn.

By the way, we already have one but it's pretty outdate, see [plan/syllabus.md](https://github.com/kottans/frontend/blob/master/plan/syllabus.md)

**Comment by OleksiyRudenko** [comment]
@viktor-yakubiv 
> Let's leave numbering for regular people, e.g. 1,2,3.

I am ok with this, no doubt we can manage TOC in any `.md` doc easily.
Actually, my initial idea was more addressed at `taskXXXX.md` files: to keep those ordered and avoid renaming all files every time we decide to insert new task.

The only problem with having ordinal numbering with natural series is that at some point of time reference to e.g. Task 5 somewhere in chat may mislead the reader.

**Comment by yevhenorlov** [comment]
@OleksiyRudenko I really like the idea of task codes and see the problems they solve. And @viktor-yakubiv has a valid point.

To avoid confusion, I suggest a compromise: we use the codes "as is" in file names (`0020.md` etc), and put the ToC on the first page. In ToC, we use dot-separated formatting of codes to familiarize students with what different parts of the code mean. For example:

```
0. Remote tasks

0.0 General Basics

0.0.20 Git basics (0)
0.0.30 Linux CLI and Networking
0.0.40 VCS (hello gitty), GitHub and collaboration

0.1 Frontend basics

0.1.10 Intro to HTML & CSS (03)
0.1.20 Responsive Web Design (04)
0.1.30 Intro to JS (05)
...
```

etc.

**Comment by viktor-yakubiv** [comment]
There is an another and better option.

1. Move tasks to directories, e.g. `tasks`, `tasks/pizza-app`, `tasks/layouts`...
2. Call task files meaningfully, e.g. `tasks/git.md`
3. Create _Contents_ section in `README.md` and make links to all the files in right order

**Comment by IgorKurkov** [comment]
I think this system will be rejected as soon as we will see that students will be confused by a lot of numbers, codes and something else. And in the last course, we saw the same situation, when mentors want to bring us component' structure in few days but they rebuild his course curriculum of this subject to few months because all students were not ready to understand so hard information. We build a system. The life make changes :) Let's make the system simpler IMHO

**Comment by OleksiyRudenko** [comment]
You're totally right. Take a look at master structure

**Comment by IgorKurkov** [comment]
Yes, I already saw them. Now they are more understandable, of course. You do awesome job :)

**Comment by OleksiyRudenko** [comment]
@viktor-yakubiv just did a PR while we were discussing the best approach :wink:
