### ISSUE TITLE
[2018-10-12] Supplement remote phase English-only materials with translated counterparts

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/frontend#96]
Current training resources for remote phase fit the course targets. However most of those offer English-only narration and captioning which affects information digesting for many students.

Supplementing the sources with translated counterparts or at least similar materials on the same topics in students' native language would improve learning tempo.

Deadline for the remote phase tasks is 2018-10-12

**Comment by dmk1111** [comment]
How do you suggest to predict student’s native language? Should it be Ukrainian, Russian or Polish? Or all of them?
I suppose future developers should be able to read in English and to find proper information by themselves.

**Comment by OleksiyRudenko** [comment]
@dmk1111 Good point. 

1. Current materials are all in English as a primary language. This will remain as it is.
If any different language alternative material to be added it will be marked as secondary and can be ignored without any harm to learning progress.

2. This course intramural phase from past experience is all Ukrainian/Russian. This fact determines current choice of languages for secondary materials. However should practical need in other languages arise I do not see reasons to reject. It's all of the matter on how to arrange the information so it would remain digestible.

**Comment by IgorKurkov** [comment]
I can suggest add in HTML task first free of paid 200 lessons of HTML academy - it really result-oriented and built very wise. They will very helpful for newbies

**Comment by OleksiyRudenko** [comment]
Can you, please, PR the changes?

**Comment by IgorKurkov** [comment]
Sure, it already exist in additional materials as mention, but I prefer to move it near english HTML course and define count of lessons.

**Comment by IgorKurkov** [comment]
> Can you, please, PR the changes?

done

**Comment by ganolmc** [comment]
As a possible variant for RU variant of Intro to JS - https://github.com/azat-io/you-dont-know-js-ru/tree/master/up%20%26%20going

**Comment by OleksiyRudenko** [comment]
@ganolmc thanks, added as a read-now-or-later item to not take much extra time.

Please, feel free [contributing](https://github.com/kottans/frontend/blob/master/CONTRIBUTING.md) on your own. 😉
